# This file is a template, and might need editing before it works on your project.
# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
image: mg:jdk-8

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script: gradle release && mvn deploy:deploy-file -DgroupId=com.birmoe.osp -DartifactId=grouplocalzie -Dversion=0.0.1_a1 -Dpackaging=jar -Dfile=build/libs/GroupLocalizeForTC11-0.0.1.00018_RELEASED.jar -Durl=http://nas.qistchan.com:8081/repository/docker-hosted/ -DrepositoryId=Hamster-nexus3
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

